# Generated by Django 4.1.6 on 2023-02-24 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user_employee_profile_u_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_profile',
            old_name='u_user',
            new_name='user',
        ),
    ]
