# Generated by Django 4.1.6 on 2023-03-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_employee_profile_has_used_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile/profile.png', null=True, upload_to='profile/'),
        ),
    ]
