# Generated by Django 4.1.6 on 2023-03-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_employee_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_profile',
            name='bank_account',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee_profile',
            name='dob',
            field=models.DateField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='employee_profile',
            name='nid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
