# Generated by Django 4.1.6 on 2023-03-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_employee_profile_city_employee_profile_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_profile',
            name='agreement_1',
            field=models.ImageField(blank=True, null=True, upload_to='agreement/'),
        ),
        migrations.AddField(
            model_name='employee_profile',
            name='agreement_2',
            field=models.ImageField(blank=True, null=True, upload_to='agreement/'),
        ),
    ]
