# Generated by Django 4.1.6 on 2023-02-12 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_employee_profile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to='cv')),
                ('profile_pic', models.ImageField(upload_to='cv')),
                ('agreement', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=255)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee_profile')),
            ],
        ),
    ]
