# Generated by Django 4.1.6 on 2023-02-21 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_vacancy', '0002_remove_employee_cv_agreement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_cv',
            old_name='user',
            new_name='p_user',
        ),
    ]
