# Generated by Django 4.1.6 on 2023-03-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_vacancy', '0007_employee_cv_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_cv',
            name='record_number',
            field=models.IntegerField(default=0),
        ),
    ]
