# Generated by Django 4.1.6 on 2023-03-21 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_employee_profile_agreement_1_and_more'),
        ('job_vacancy', '0010_employee_cv_record_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_cv',
            name='p_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee_profile'),
        ),
    ]
