# Generated by Django 4.1.6 on 2023-03-22 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_employee_profile_agreement_1_and_more'),
        ('job_vacancy', '0011_alter_employee_cv_p_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_cv',
            name='record_number',
        ),
        migrations.AlterField(
            model_name='employee_cv',
            name='p_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.employee_profile'),
        ),
    ]
