# Generated by Django 4.1.6 on 2023-03-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_vacancy', '0014_alter_employee_cv_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_cv',
            name='interestedfor',
            field=models.CharField(blank=True, choices=[('WFH', 'WFH'), ('WFO', 'WFO')], default='WFH', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee_cv',
            name='position',
            field=models.CharField(blank=True, choices=[('PM', 'PM'), ('APM', 'APM'), ('Trainner', 'Trainner'), ('Operator', 'Operator')], default='PM', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee_cv',
            name='shifttime',
            field=models.CharField(blank=True, choices=[('Day', 'Day'), ('Evening', 'Evening')], default='Day', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee_cv',
            name='startingdate',
            field=models.DateField(blank=True, max_length=8, null=True),
        ),
    ]
