# Generated by Django 4.1.6 on 2023-03-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_vacancy', '0017_employee_cv_agreementlicens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_cv',
            name='position',
        ),
        migrations.AddField(
            model_name='employee_cv',
            name='dateofbirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee_cv',
            name='education',
            field=models.CharField(blank=True, choices=[('Completed 10 years school', 'Completed 10 years school'), ('Completed 10 years school & High School', 'Completed 10 years school & High School'), ('University Degree', 'University Degree'), ('University Degree - Masters', 'University Degree - Masters'), ('Technical Degree', 'Technical Degree'), ('Others', 'Others')], default='Completed 10 years school', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee_cv',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee_cv',
            name='nationalid',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employee_cv',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee_cv',
            name='shifttime',
            field=models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Evening', 'Evening'), ('Night', 'Night')], default='Day', max_length=255, null=True),
        ),
    ]
