# Generated by Django 4.1.6 on 2023-03-29 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_employee_profile_license'),
        ('job_vacancy', '0018_remove_employee_cv_position_employee_cv_dateofbirth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid_birthcertificate', models.FileField(upload_to='documents/')),
                ('education_certificate', models.FileField(upload_to='documents/')),
                ('chairman_certificate', models.FileField(upload_to='documents/')),
                ('testimonial', models.FileField(upload_to='documents/')),
                ('p_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.employee_profile')),
            ],
        ),
    ]
