# Generated by Django 4.1.6 on 2023-03-31 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_vacancy', '0019_documents_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_cv',
            name='country',
            field=models.CharField(blank=True, choices=[('Bangladesh', 'Bangladesh'), ('India', 'India'), ('Srilanka', 'Srilanka'), ('Nepal', 'Nepal'), ('Kenya', 'Kenya')], default='Where are you from?', max_length=255, null=True),
        ),
    ]
